ARG BASE_IMAGE=vicamo/docker:%%VERSION%%-%%SUITE%%-%%ARCH%%

FROM ${BASE_IMAGE}

RUN apt-get update --quiet \
	&& apt-get install --no-install-recommends --yes \
		git \
		openssh-client \
	&& rm -rf /var/lib/apt
